import { Inter } from 'next/font/google';
import BodyWrapper from '@/components/BodyWrapper';
import '@/assets/css/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BodyWrapper>{children}</BodyWrapper>
      </body>
    </html>
  );
}
